### ISSUE TITLE
Etude 7-01 references a "example download area" which does not exist

### ISSUE THREAD

**Issue by sndwch** [oreillymedia/etudes-for-elixir#32]
courses.csv exists in the repo, but not in the http://chimera.labs.oreilly.com/ site as far as I can tell. The text says "URL goes here" :smile:

**Comment by assembler** [comment]
+1

**Comment by assembler** [comment]
https://github.com/oreillymedia/etudes-for-elixir/blob/master/code/ch07-01/courses.csv
